description: ''
id: AlienVaultOTX Test
inputs: []
name: AlienVaultOTX Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: b256b1bb-e449-47f5-8afc-9d3fe446dd63
      iscommand: false
      name: ''
      version: -1
    taskid: b256b1bb-e449-47f5-8afc-9d3fe446dd63
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: c00debdb-5a50-4217-8a83-486cf0cae811
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: c00debdb-5a50-4217-8a83-486cf0cae811
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      long: {}
      retries: {}
      sampleSize: {}
      submitWait: {}
      threshold: {}
      url:
        simple: https://social.technet.microsoft.com/Forums/en-US/4bd3093f-8e2d-42df-bc64-330788d18801/to-test-ms-ata?forum=mata
      wait: {}
    separatecontext: false
    task:
      brand: ''
      description: Query url in AlienVault OTX
      id: 745db237-7885-4c26-86eb-47be24f3b117
      iscommand: true
      name: AlienVault !url
      script: AlienVault OTX|||url
      type: regular
      version: -1
    taskid: 745db237-7885-4c26-86eb-47be24f3b117
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      fullResponse: {}
      ip:
        simple: 1.2.3.4
      long: {}
      retries: {}
      sampleSize: {}
      threshold: {}
      wait: {}
    separatecontext: false
    task:
      brand: ''
      description: Check IP Reputation
      id: a0ec5b8c-97f1-4044-89ab-61289e000dcc
      iscommand: true
      name: AlienVault !ip
      script: AlienVault OTX|||ip
      type: regular
      version: -1
    taskid: a0ec5b8c-97f1-4044-89ab-61289e000dcc
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 550\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      ip:
        simple: 2603:10b6:0:54::19
    separatecontext: false
    task:
      brand: ''
      description: Query IP in AlienVault OTX
      id: e2539ad6-8365-473d-8182-7d24c5652155
      iscommand: true
      name: AlienVault !ipv6
      script: AlienVault OTX|||ipv6
      type: regular
      version: -1
    taskid: e2539ad6-8365-473d-8182-7d24c5652155
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    note: false
    scriptarguments:
      domain:
        simple: demisto.com
      fullResponse: {}
      long: {}
      retries: {}
      sampleSize: {}
      threshold: {}
      wait: {}
    separatecontext: false
    task:
      brand: ''
      description: Check domain reputation
      id: 63967c91-8a2c-436f-8065-1947766a0004
      iscommand: true
      name: AlienVault domain
      script: AlienVault OTX|||domain
      type: regular
      version: -1
    taskid: 63967c91-8a2c-436f-8065-1947766a0004
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 940,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
