description: ''
fromversion: 3.5.0
id: account_enrichment_-_generic_test
inputs: []
name: Account Enrichment - Generic Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '4'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: f25242cf-a32c-4bab-887e-0e60ef1df2cc
      iscommand: false
      name: ''
      version: -1
    taskid: f25242cf-a32c-4bab-887e-0e60ef1df2cc
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '3':
    id: '3'
    scriptarguments:
      expectedValue: {}
      fields:
        simple: Type,ID
      path:
        simple: Account
    separatecontext: false
    task:
      brand: ''
      description: '-'
      id: 04fad9d5-8b71-408a-8268-d999637113f9
      iscommand: false
      name: Verify account fields
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: 04fad9d5-8b71-408a-8268-d999637113f9
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '4':
    id: '4'
    nexttasks:
      '#none#':
      - '5'
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 60331414-cfec-4bfb-8b92-f5ecace8c187
      iscommand: false
      name: Delete context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 60331414-cfec-4bfb-8b92-f5ecace8c187
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '5':
    id: '5'
    nexttasks:
      '#none#':
      - '6'
    scriptarguments:
      append:
        simple: 'true'
      key:
        simple: ExampleAccount.Username
      value:
        simple: admin
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 61172af1-2c47-407e-84f7-2b9e6aa9e4de
      iscommand: false
      name: 'add username #1'
      scriptName: Set
      type: regular
      version: -1
    taskid: 61172af1-2c47-407e-84f7-2b9e6aa9e4de
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '6':
    id: '6'
    nexttasks:
      '#none#':
      - '7'
    scriptarguments:
      append:
        simple: 'true'
      key:
        simple: ExampleAccount.Username
      value:
        simple: administrator
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 0496f253-92ec-474f-872b-ef3901241fd0
      iscommand: false
      name: 'add username #2'
      scriptName: Set
      type: regular
      version: -1
    taskid: 0496f253-92ec-474f-872b-ef3901241fd0
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '7':
    id: '7'
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '3'
    scriptarguments:
      Username:
        simple: ${ExampleAccount.Username}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 9f90f181-6c3f-4917-8943-1a329005daef
      iscommand: false
      name: Account Enrichment - Generic
      playbookName: Account Enrichment - Generic
      type: playbook
      version: -1
    taskid: 9f90f181-6c3f-4917-8943-1a329005daef
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 725\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 940,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
