id: DocumentationTest
inputs: []
name: DocumentationTest
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '3'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 6be27b4d-b75b-4cb4-8e6f-23cbbb687f57
      iscommand: false
      name: ''
      version: -1
    taskid: 6be27b4d-b75b-4cb4-8e6f-23cbbb687f57
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      body: {}
      filename: {}
      headers: {}
      insecure: {}
      method:
        simple: GET
      password:
        simple: '{ENCRYPTED}DHE4wxi5Rhfbf/hom8IoiHsM23L+y4na46w5limTjwtiIzV1c5DmdqqWKfY4HDbzTO5Yc3LPH89Rzfyl43AWqQ=='
      proxy: {}
      saveAsFile:
        simple: 'yes'
      unsecure: {}
      url:
        simple: https://github.com/demisto/content/raw/master/Packs/ipinfo/Integrations/integration-Ipinfo.yml
      username: {}
    separatecontext: false
    task:
      brand: ''
      id: 83f4d032-2d4a-4877-8dde-703a4b7883dd
      iscommand: false
      name: Download Ipinfo integration
      scriptName: http
      type: regular
      version: -1
    taskid: 83f4d032-2d4a-4877-8dde-703a4b7883dd
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '2':
    id: '2'
    note: false
    scriptarguments:
      addInfo: {}
      commands:
        simple: '!ipinfo_field ip=8.8.8.8 field=city

          !ip ip=8.8.8.8 using-brand=ipinfo'
      entryID:
        simple: ${File.EntryID}
      fetchedData: {}
      limit: {}
      overview: {}
      setupOnIntegration: {}
      troubleshooting: {}
      useCases: {}
      withErrors:
        simple: 'True'
    separatecontext: false
    task:
      brand: ''
      id: 308bf576-3a59-40a0-85d7-53ed855f9de9
      iscommand: false
      name: Generate Docs
      scriptName: DocumentationAutomation
      type: regular
      version: -1
    taskid: 308bf576-3a59-40a0-85d7-53ed855f9de9
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      id: 2123fa51-37f7-40e9-83ae-a2eefc463435
      iscommand: false
      name: Start Clean
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 2123fa51-37f7-40e9-83ae-a2eefc463435
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 590,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
