description: ''
id: ShodanTest
inputs: []
name: ShodanTest
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '1'
    reputationcalc: 0
    separatecontext: false
    task:
      brand: ''
      id: f50ccca6-eb90-4d74-8299-c128a80ccba9
      iscommand: false
      name: ''
      version: -1
    taskid: f50ccca6-eb90-4d74-8299-c128a80ccba9
    type: start
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '2'
    reputationcalc: 0
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 5e24c48c-eb4e-44d4-8d41-21dacb7caa99
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 5e24c48c-eb4e-44d4-8d41-21dacb7caa99
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 195\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '4'
      - '3'
      - '5'
    reputationcalc: 0
    scriptarguments:
      ip:
        simple: 1.1.1.1
    separatecontext: false
    task:
      brand: Shodan
      description: Check IP reputation (when information is available, returns a JSON
        with details).  Uses all configured Threat Intelligence feeds
      id: e0973ef7-c26c-45d4-815a-7debb4982073
      iscommand: true
      name: ip
      script: Shodan|||ip
      type: regular
      version: -1
    taskid: e0973ef7-c26c-45d4-815a-7debb4982073
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    reputationcalc: 0
    scriptarguments:
      expectedValue: {}
      fields:
        simple: Description,Country,Location
      path:
        simple: IP.Geo
    separatecontext: false
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: b1ba2075-3fc1-4d9e-8c51-a4dbc2347d05
      iscommand: false
      name: VerifyContext Geo
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: b1ba2075-3fc1-4d9e-8c51-a4dbc2347d05
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 51,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    reputationcalc: 0
    scriptarguments:
      expectedValue: {}
      fields:
        simple: Address
      path:
        simple: IP
    separatecontext: false
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: 5909d66a-33a7-4b2d-8d17-0bbe69f90bb4
      iscommand: false
      name: VerifyContext Address
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: 5909d66a-33a7-4b2d-8d17-0bbe69f90bb4
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 545\n  }\n}"
  '5':
    id: '5'
    reputationcalc: 0
    scriptarguments:
      expectedValue: {}
      fields:
        simple: Hostname
      path:
        simple: IP
    separatecontext: false
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: 4ee20456-5491-468c-8564-7d6f35d389be
      iscommand: false
      name: VerifyContext Address
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: 4ee20456-5491-468c-8564-7d6f35d389be
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 916,\n    \"y\": 545\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 590,\n      \"width\": 1245,\n      \"x\": 51,\n      \"y\": 50\n\
  \    }\n  }\n}"
