description: A test for email address enrichment. Currently, due to issues, the test
  does not check all domain squatting results or whether the email addresses were
  detected as internal or external.
fromversion: 4.1.0
id: Email Address Enrichment - Generic v2 - Test
inputs:
- description: A comma-separated list of internal domains
  key: InternalDomains
  required: false
  value:
    simple: demisto.com, demistodev.com
name: Email Address Enrichment - Generic v2 - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 22a2e035-f857-417e-81cb-308b8a9dfec8
      iscommand: false
      name: ''
      version: -1
    taskid: 22a2e035-f857-417e-81cb-308b8a9dfec8
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      Domain:
        complex:
          accessor: Name
          root: Domain
          transformers:
          - operator: uniq
      Email:
        complex:
          accessor: Email.Address
          root: Account
          transformers:
          - operator: uniq
    separatecontext: true
    task:
      brand: ''
      id: 4181b3ee-0d7b-446f-81d0-0597eaecb22d
      iscommand: false
      name: Email Address Enrichment - Generic v2
      playbookName: Email Address Enrichment - Generic v2
      type: playbook
      version: -1
    taskid: 4181b3ee-0d7b-446f-81d0-0597eaecb22d
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 560\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    reputationcalc: 1
    scriptarguments:
      append: {}
      key:
        simple: Domain.Name
      value:
        simple: '["demisto.com", "demist0.com", "domainthatdoesntexist.co.uk", "someotherdomainandnoemailforit.bro"]'
    separatecontext: false
    task:
      brand: ''
      description: Sets a value into the context with the given context key
      id: fdf1e7b5-68e7-4199-825b-ee7878b64f8f
      iscommand: false
      name: Set domains to context
      scriptName: Set
      type: regular
      version: -1
    taskid: fdf1e7b5-68e7-4199-825b-ee7878b64f8f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 230,\n    \"y\": 360\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    reputationcalc: 1
    scriptarguments:
      append: {}
      key:
        simple: Account.Email.Address
      value:
        simple: '["geverwithnoname@domainthatdoesntexist.co.uk", "soso@demisto.com",
          "koko@demisto.com", "user1@domain.com"]'
    separatecontext: false
    task:
      brand: ''
      description: Sets a value into the context with the given context key
      id: 179ca0a7-2447-4dfd-8083-c73f1669ec5f
      iscommand: false
      name: Set email addresses to context
      scriptName: Set
      type: regular
      version: -1
    taskid: 179ca0a7-2447-4dfd-8083-c73f1669ec5f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 670,\n    \"y\": 360\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
      - '3'
    note: false
    reputationcalc: 1
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Deletes context for a fresh start of this test.
      id: 43deb7e7-c488-46ec-8408-d1a303a4b563
      iscommand: false
      name: Delete context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 43deb7e7-c488-46ec-8408-d1a303a4b563
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 180\n  }\n}"
  '5':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Score
                root: DBotScore
          operator: isEqualNumber
          right:
            value:
              simple: '2'
      label: 'yes'
    id: '5'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '7'
      'yes':
      - '6'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: d9227bdc-084f-4652-8a86-10659a4c8fe4
      iscommand: false
      name: Was there a case of domain squatting?
      type: condition
      version: -1
    taskid: d9227bdc-084f-4652-8a86-10659a4c8fe4
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 740\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 02372e49-2953-4bed-844a-ed4c5011234f
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 02372e49-2953-4bed-844a-ed4c5011234f
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 1120\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    reputationcalc: 1
    scriptarguments:
      message:
        simple: Domain squatting should have been detected, but wasn't.
    separatecontext: false
    task:
      brand: ''
      description: Fail the test if domain squatting was not detected.
      id: 3bc8b6a6-35d5-46af-8180-ab5c74431165
      iscommand: false
      name: Make test fail
      scriptName: PrintErrorEntry
      type: regular
      version: -1
    taskid: 3bc8b6a6-35d5-46af-8180-ab5c74431165
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 870,\n    \"y\": 925\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {\n    \"5_6_yes\": 0.47,\n    \"5_7_#default#\"\
  : 0.42\n  },\n  \"paper\": {\n    \"dimensions\": {\n      \"height\": 1135,\n \
  \     \"width\": 1020,\n      \"x\": 230,\n      \"y\": 50\n    }\n  }\n}"
