description: ''
id: JiraCreateIssue-example-test
inputs: []
name: JiraCreateIssue-example-test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: ee963608-6c73-44fd-8e11-12b9ce752e20
      iscommand: false
      name: ''
      version: -1
    taskid: ee963608-6c73-44fd-8e11-12b9ce752e20
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: f9e3c914-4de1-4c26-89de-d5505a075e9d
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: f9e3c914-4de1-4c26-89de-d5505a075e9d
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 170\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      assignee: {}
      description:
        simple: '"jira descriptions" '
      dueDate: {}
      issueTypeId:
        simple: '10001'
      issueTypeName:
        simple: Incident
      labels: {}
      parentIssueId: {}
      parentIssueKey: {}
      priority: {}
      projectKey:
        simple: DEM
      projectName: {}
      reporter: {}
      summary:
        simple: '"jira playbook test"'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: b716384f-1231-4d76-8558-f302af7cc086
      iscommand: false
      name: Jira create generic Issue
      scriptName: JiraCreateIssue-example
      type: regular
      version: -1
    taskid: b716384f-1231-4d76-8558-f302af7cc086
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 320\n  }\n}"
  '3':
    id: '3'
    note: false
    scriptarguments:
      issueIdOrKey:
        simple: ${Ticket.Id}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 2dd6dbe2-fd37-4739-8ec9-bef4008b22a2
      iscommand: true
      name: delete issue
      script: '|||jira-delete-issue'
      type: regular
      version: -1
    taskid: 2dd6dbe2-fd37-4739-8ec9-bef4008b22a2
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 480\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 525,\n      \"width\": 380,\n      \"x\": 450,\n      \"y\": 50\n\
  \    }\n  }\n}"
