description: ''
fromversion: 3.5.0
id: extract_indicators_-_generic_-_test
inputs: []
name: Extract Indicators - Generic - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '5'
    separatecontext: false
    task:
      brand: ''
      id: 51459ac5-98bb-45f5-8761-e310b7553e2a
      iscommand: false
      name: ''
      version: -1
    taskid: 51459ac5-98bb-45f5-8761-e310b7553e2a
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '3'
    scriptarguments:
      addLabels: {}
      customFieldName: {}
      customFieldValue: {}
      details: {}
      extend-context: {}
      labels:
        simple: '[{"url": "https://www.threathq.com"}, {"ip": "123.57.77.130"}, {"hash":
          "666a8dbc172bcf7cd698bf95e5b58de17535121fed7de5ce1349db4446a1fa5c"}]'
      name: {}
      owner: {}
      playbook: {}
      severity: {}
      stage: {}
      type: {}
      updatePlaybookForType: {}
    separatecontext: false
    task:
      brand: ''
      description: Add indicators to the incidents, for the sub playbook to extract.
      id: 0a7acc45-5844-4b3b-8ec7-8e02f4408a9c
      iscommand: false
      name: Add Labels to the Incident
      scriptName: IncidentSet
      type: regular
      version: -1
    taskid: 0a7acc45-5844-4b3b-8ec7-8e02f4408a9c
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '4'
    separatecontext: true
    task:
      brand: ''
      id: bf9d2db9-6476-4f30-8c2c-6115d3a0d93d
      iscommand: false
      name: Extract Indicators - Generic
      playbookName: Extract Indicators - Generic
      type: playbook
      version: -1
    taskid: bf9d2db9-6476-4f30-8c2c-6115d3a0d93d
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    nexttasks:
      '#none#':
      - '6'
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: URL.Data
    separatecontext: false
    task:
      brand: ''
      id: dbe64c77-8f94-4883-847a-fd15e8d9a901
      iscommand: false
      name: Verify indicators were extracted
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: dbe64c77-8f94-4883-847a-fd15e8d9a901
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '5':
    id: '5'
    nexttasks:
      '#none#':
      - '2'
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    task:
      brand: ''
      id: c561f70b-88dc-44fd-8b08-4f2033972358
      iscommand: false
      name: Clear context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: c561f70b-88dc-44fd-8b08-4f2033972358
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '6':
    id: '6'
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: IP.Address
    separatecontext: false
    task:
      brand: ''
      id: 17a056ba-b5b5-4265-857c-339d5dc61bd5
      iscommand: false
      name: Verify indicators were extracted
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: 17a056ba-b5b5-4265-857c-339d5dc61bd5
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 900\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 945,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
