id: blockip_test_playbook
inputs: []
name: blockip_test_playbook
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 43365063-60a1-4234-8fc9-0d206e581395
      iscommand: false
      name: ''
      version: -1
    taskid: 43365063-60a1-4234-8fc9-0d206e581395
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    note: false
    scriptarguments:
      direction:
        simple: both
      ip:
        simple: 10.10.10.10
      ipname:
        simple: nameip
      rulename:
        simple: test
    separatecontext: false
    task:
      brand: ''
      description: Blocks IP in configured firewall
      id: d4ee0e67-f6ad-4fdb-8254-c813b8c38f0c
      iscommand: false
      name: BlockIP
      scriptName: BlockIP
      type: regular
      version: -1
    taskid: d4ee0e67-f6ad-4fdb-8254-c813b8c38f0c
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 230\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 275,\n      \"width\": 380,\n      \"x\": 450,\n      \"y\": 50\n\
  \    }\n  }\n}"
