description: A test for the Account Enrichment - Generic v2 playbook.
fromversion: 4.1.0
id: Account Enrichment - Generic v2 - Test
inputs: []
name: Account Enrichment - Generic v2 - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: e730f65f-dac8-4988-8603-1f0d4d66dad6
      iscommand: false
      name: ''
      version: -1
    taskid: e730f65f-dac8-4988-8603-1f0d4d66dad6
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    reputationcalc: 1
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Clear the context for a fresh start of the test.
      id: b13d4e0f-214d-4a6e-8130-51aa93b7116a
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: b13d4e0f-214d-4a6e-8130-51aa93b7116a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 200\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: Account.Samaccountname
                    operator: isEqualString
                    right:
                      value:
                        simple: Guest
                root: Account
          operator: isExists
      label: 'yes'
    id: '3'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '6'
      'yes':
      - '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 0df4f192-b17c-4338-8329-1b0b79a03774
      iscommand: false
      name: Were the accounts enriched?
      type: condition
      version: -1
    taskid: 0df4f192-b17c-4338-8329-1b0b79a03774
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 710\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    reputationcalc: 1
    scriptarguments:
      append: {}
      key:
        simple: Account.Username
      value:
        simple: '["Guest", "user1551547345"]'
    separatecontext: false
    task:
      brand: ''
      description: Sets a value into the context with the given context key.
      id: 03439110-2230-4879-86e4-971f43a896b6
      iscommand: false
      name: Set account usernames in context
      scriptName: Set
      type: regular
      version: -1
    taskid: 03439110-2230-4879-86e4-971f43a896b6
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 370\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: e317c164-089b-493b-8bf8-a4c7f790cf6a
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: e317c164-089b-493b-8bf8-a4c7f790cf6a
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 1060\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      message:
        simple: The accounts were not enriched as expected (did not get the outputs
          that we expected from the Account Enrichment - Generic playbook). Check
          if the users still exist in the integrations used by that playbook (Active
          Directory, for example). Also checks that the outputs are there and that
          they are the outputs we are checking for.
    separatecontext: false
    task:
      brand: ''
      description: Prints an error entry with a given message.
      id: 47411382-86d3-4401-8dd0-d698b5c39032
      iscommand: false
      name: Make test fail
      scriptName: PrintErrorEntry
      type: regular
      version: -1
    taskid: 47411382-86d3-4401-8dd0-d698b5c39032
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 770,\n    \"y\": 880\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      Username:
        complex:
          accessor: Username
          root: Account
          transformers:
          - operator: uniq
    separatecontext: true
    task:
      brand: ''
      id: 5b9ee1a1-609b-4b18-8840-27926712c229
      iscommand: false
      name: Account Enrichment - Generic v2
      playbookName: Account Enrichment - Generic v2
      type: playbook
      version: -1
    taskid: 5b9ee1a1-609b-4b18-8840-27926712c229
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 540\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1075,\n      \"width\": 700,\n      \"x\": 450,\n      \"y\":\
  \ 50\n    }\n  }\n}"
