description: Creates a text file and tests ReadFile script
fromversion: 4.1.0
id: ReadPDFFile-Test
inputs: []
name: ReadPDFFile-Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: c9c99f1d-5962-49bf-8aef-26d2ed366ec9
      iscommand: false
      name: ''
      version: -1
    taskid: c9c99f1d-5962-49bf-8aef-26d2ed366ec9
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      body: {}
      filename: {}
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: 'yes'
      unsecure: {}
      url:
        simple: https://github.com/demisto/content/raw/master/TestData/pdf_noeof.pdf
      username: {}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 49dd1b55-421b-4bf7-8e5b-7ab17a00c628
      iscommand: false
      name: 'Get corrupted file '
      scriptName: http
      type: regular
      version: -1
    taskid: 49dd1b55-421b-4bf7-8e5b-7ab17a00c628
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 370\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '15'
    note: false
    scriptarguments:
      body: {}
      filename: {}
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: 'yes'
      unsecure: {}
      url:
        simple: https://github.com/demisto/content/raw/master/TestData/pdf-example-password.pdf
      username: {}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: dba3165b-1c0c-40c4-8e3b-0f86deeeb057
      iscommand: false
      name: 'Get encrypted file '
      scriptName: http
      type: regular
      version: -1
    taskid: dba3165b-1c0c-40c4-8e3b-0f86deeeb057
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1595\n  }\n}"
  '11':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Score
          operator: isEqualString
          right:
            value:
              simple: '2'
      label: 'yes'
    id: '11'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '13'
      'yes':
      - '9'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 0573b421-d80e-4709-8797-27e0a5a2090b
      iscommand: false
      name: Check if encrypted
      type: condition
      version: -1
    taskid: 0573b421-d80e-4709-8797-27e0a5a2090b
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1945\n  }\n}"
  '12':
    id: '12'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '10'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: b00f61a4-8240-4807-8964-88c7eab76c63
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: b00f61a4-8240-4807-8964-88c7eab76c63
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1420\n  }\n}"
  '13':
    id: '13'
    ignoreworker: false
    note: false
    scriptarguments:
      message:
        simple: 'File was not marked as suspicious '
    separatecontext: false
    task:
      brand: ''
      description: Prints an error entry with a given message
      id: 3d4ebf33-ed49-4b8a-831a-1a5b85c5e63e
      iscommand: false
      name: Print Error
      scriptName: PrintErrorEntry
      type: regular
      version: -1
    taskid: 3d4ebf33-ed49-4b8a-831a-1a5b85c5e63e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2120\n  }\n}"
  '14':
    id: '14'
    ignoreworker: false
    note: false
    scriptarguments:
      message:
        simple: 'File was not marked as suspicious '
    separatecontext: false
    task:
      brand: ''
      description: Prints an error entry with a given message
      id: 171155c3-d937-4a73-8b4a-2eb4ef11860c
      iscommand: false
      name: Print Error
      scriptName: PrintErrorEntry
      type: regular
      version: -1
    taskid: 171155c3-d937-4a73-8b4a-2eb4ef11860c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 695,\n    \"y\": 895\n  }\n}"
  '15':
    continueonerror: true
    id: '15'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '11'
    note: false
    scriptarguments:
      entryID:
        simple: ${File.EntryID}
      maxFileSize: {}
    separatecontext: false
    task:
      brand: ''
      description: Load the contents and metadata of a PDF file into context.
      id: 3caf38fe-ae5d-4b49-849f-bdef78e14305
      iscommand: false
      name: Read PDF
      scriptName: ReadPDFFile
      type: regular
      version: -1
    taskid: 3caf38fe-ae5d-4b49-849f-bdef78e14305
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1770\n  }\n}"
  '2':
    continueonerror: true
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      entryID:
        simple: ${File.EntryID}
      maxFileSize: {}
    separatecontext: false
    task:
      brand: ''
      description: Load the contents and metadata of a PDF file into context.
      id: 79a37f01-2580-4c2e-859d-85bac89260ce
      iscommand: false
      name: Read PDF
      scriptName: ReadPDFFile
      type: regular
      version: -1
    taskid: 79a37f01-2580-4c2e-859d-85bac89260ce
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 545\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 6cbbd724-5c83-43ed-8c72-733323e7f66b
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 6cbbd724-5c83-43ed-8c72-733323e7f66b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 195\n  }\n}"
  '5':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Score
          operator: isEqualString
          right:
            value:
              simple: '2'
      label: 'yes'
    id: '5'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '14'
      'yes':
      - '6'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: ef22626a-506b-4bb1-881f-11ea01fe0b23
      iscommand: false
      name: 'Check if PSEOF '
      type: condition
      version: -1
    taskid: ef22626a-506b-4bb1-881f-11ea01fe0b23
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 720\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: e7564bda-5012-4908-8fb6-de73bd2d2276
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: e7564bda-5012-4908-8fb6-de73bd2d2276
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 895\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    scriptarguments:
      body: {}
      filename: {}
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: 'yes'
      unsecure: {}
      url:
        simple: https://github.com/demisto/content/raw/master/TestData/pdfworking.pdf
      username: {}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 4b8ca77e-8e46-40fa-8e5d-98e7dfe53e36
      iscommand: false
      name: Get working PDF
      scriptName: http
      type: regular
      version: -1
    taskid: 4b8ca77e-8e46-40fa-8e5d-98e7dfe53e36
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1070\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '12'
    note: false
    scriptarguments:
      entryID:
        simple: ${File.EntryID}
      maxFileSize: {}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: eec65d20-9dec-4a6c-8851-ccd87bcfdcfb
      iscommand: false
      name: Read PDF
      scriptName: ReadPDFFile
      type: regular
      version: -1
    taskid: eec65d20-9dec-4a6c-8851-ccd87bcfdcfb
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1245\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: e58e419a-6a14-4cc2-8fa3-fab1b6888cb0
      iscommand: false
      name: End of test
      type: title
      version: -1
    taskid: e58e419a-6a14-4cc2-8fa3-fab1b6888cb0
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 2135\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 2165,\n      \"width\": 1025,\n      \"x\": 50,\n      \"y\":\
  \ 50\n    }\n  }\n}"
