description: Test CreatePhishingClassifierML playbook
fromversion: 4.1.0
id: CreatePhishingClassifierMLTest
inputs: []
name: Create Phishing Classifier ML Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '6'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: db64e108-0b5f-447c-898e-252858a97819
      iscommand: false
      name: ''
      version: -1
    taskid: db64e108-0b5f-447c-898e-252858a97819
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '12'
    note: false
    scriptarguments:
      emailSubjectKey:
        simple: ${EmailSujbectKey}
      emailTagKey:
        simple: ${EmailTagKey}
      emailTextKey:
        simple: ${EmailBodyKey}
      hashData:
        simple: 'no'
      historicalDataFileListName:
        simple: historicFileTest
      incidentsEvaluationQuery:
        simple: ${IncidentsQuery}
      incidentsTrainingQuery:
        simple: ${IncidentsQuery}
      isContextNeeded:
        simple: 'yes'
      maxIncidentsToFetchOnTraining:
        simple: '2000'
      modelListStoreName:
        simple: phishing_model_test
      phishingLabels:
        simple: '*'
    separatecontext: false
    task:
      brand: ''
      description: Create a phishing classifier using machine learning technique,
        based on email content
      id: 024c14f4-bbeb-4269-8dbc-399eaa48daa4
      iscommand: false
      name: CreatePhishingClassifierML
      playbookName: DBot Create Phishing Classifier
      type: playbook
      version: -1
    taskid: 024c14f4-bbeb-4269-8dbc-399eaa48daa4
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '10':
    id: '10'
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      expectedValue:
        simple: tag3
      fields: {}
      path:
        simple: DBotPredictPhishingLabel.Label
    separatecontext: false
    task:
      brand: ''
      id: fa591f3f-fc67-4cc3-8f6d-294d25855c66
      iscommand: false
      name: verify tag3
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: fa591f3f-fc67-4cc3-8f6d-294d25855c66
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1770\n  }\n}"
  '12':
    id: '12'
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      expectedValue: {}
      fields:
        simple: Precision,Recall,Size,F1
      path:
        simple: DBotPredictPhishingEvaluation
    separatecontext: false
    task:
      brand: ''
      id: d018265c-65d2-47a0-8f35-4178fea4b4fa
      iscommand: false
      name: Verify context model evaluation
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: d018265c-65d2-47a0-8f35-4178fea4b4fa
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      numberOfIncidents:
        simple: '5'
    separatecontext: false
    task:
      brand: ''
      id: 8672a476-8ec4-4699-8ce4-0c96fb964226
      iscommand: false
      name: Create incidents
      scriptName: TestCreateIncidents
      type: regular
      version: -1
    taskid: 8672a476-8ec4-4699-8ce4-0c96fb964226
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      emailBody: {}
      emailSubject:
        simple: tag1 this is a email bla bla bla
      hashData: {}
      modelListName:
        simple: ${DBotTextClassifier.ListName}
      warningThreshold: {}
    separatecontext: false
    task:
      brand: ''
      id: aea9f205-82b1-484c-8362-4c4638d43e81
      iscommand: false
      name: Predict Tag1
      scriptName: DBotPredictPhishingLabel
      type: regular
      version: -1
    taskid: aea9f205-82b1-484c-8362-4c4638d43e81
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
  '4':
    id: '4'
    nexttasks:
      '#none#':
      - '8'
    note: false
    scriptarguments:
      expectedValue:
        simple: tag1
      fields: {}
      path:
        simple: DBotPredictPhishingLabel.Label
    separatecontext: false
    task:
      brand: ''
      id: a6b723fe-fda3-4ab4-82de-a24a90c0cd51
      iscommand: false
      name: verify tag1
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: a6b723fe-fda3-4ab4-82de-a24a90c0cd51
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1245\n  }\n}"
  '5':
    id: '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 36024f92-a162-4bef-8165-7fe950bb7f48
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 36024f92-a162-4bef-8165-7fe950bb7f48
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1945\n  }\n}"
  '6':
    id: '6'
    nexttasks:
      '#none#':
      - '7'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      id: 360aa493-2459-4b6f-884e-57f777c014ed
      iscommand: false
      name: Clear context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 360aa493-2459-4b6f-884e-57f777c014ed
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '7':
    id: '7'
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      listName:
        simple: historicFileTest
    separatecontext: false
    task:
      brand: ''
      id: 09767906-11d1-430a-854b-268e8adb914b
      iscommand: false
      name: Create historic file list
      scriptName: TestCreateTagTextFile
      type: regular
      version: -1
    taskid: 09767906-11d1-430a-854b-268e8adb914b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '8':
    id: '8'
    nexttasks:
      '#none#':
      - '9'
    note: false
    scriptarguments:
      all: {}
      index: {}
      key:
        simple: DBotPredictPhishingLabel
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      id: 48a8ae8a-96cf-4349-870b-cf9c6d1fb5de
      iscommand: false
      name: clear context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 48a8ae8a-96cf-4349-870b-cf9c6d1fb5de
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1420\n  }\n}"
  '9':
    id: '9'
    nexttasks:
      '#none#':
      - '10'
    note: false
    scriptarguments:
      emailBody: {}
      emailSubject:
        simple: an3 example3
      hashData: {}
      modelListName:
        simple: ${DBotTextClassifier.ListName}
      warningThreshold: {}
    separatecontext: false
    task:
      brand: ''
      id: 52cebe3d-526d-42ff-80d5-177ce5b1b5ec
      iscommand: false
      name: Predict Tag3
      scriptName: DBotPredictPhishingLabel
      type: regular
      version: -1
    taskid: 52cebe3d-526d-42ff-80d5-177ce5b1b5ec
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1595\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1960,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
