description: ''
id: ExtractDomainTest
inputs: []
name: ExtractDomainTest
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '1'
    separatecontext: false
    task:
      brand: ''
      id: 709f1b79-ee47-45f0-882f-60e7146a9a2d
      iscommand: false
      name: ''
      version: -1
    taskid: 709f1b79-ee47-45f0-882f-60e7146a9a2d
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '2'
    scriptarguments:
      calcReputation:
        simple: 'false'
      extractFromEmails: {}
      markAsIndicator: {}
      text:
        simple: www.google.com
      tldList: {}
      urlRegex: {}
    separatecontext: false
    task:
      brand: ''
      id: 73eede55-e81f-4fcb-8119-706d1ed6d7da
      iscommand: false
      name: Extract Domain from www.google.com
      scriptName: ExtractDomain
      type: regular
      version: -1
    taskid: 73eede55-e81f-4fcb-8119-706d1ed6d7da
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 285\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '3'
    scriptarguments:
      expectedValue:
        simple: google.com
      fields: {}
      path:
        simple: Domain.Name
    separatecontext: false
    task:
      brand: ''
      id: 614aa9af-9f80-4815-8b59-b7c8e403689e
      iscommand: false
      name: verify it's google.com
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: 614aa9af-9f80-4815-8b59-b7c8e403689e
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 538\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '4'
    scriptarguments:
      calcReputation:
        simple: 'false'
      extend-context:
        simple: emailDomain=Name
      extractFromEmails: {}
      markAsIndicator: {}
      text:
        simple: meir@demisto.com
      tldList: {}
      urlRegex: {}
    separatecontext: false
    task:
      brand: ''
      id: c43e408e-5110-4e1a-8b56-3557a81f721d
      iscommand: false
      name: Extract Domain from Email
      scriptName: ExtractDomain
      type: regular
      version: -1
    taskid: c43e408e-5110-4e1a-8b56-3557a81f721d
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 741\n  }\n}"
  '4':
    id: '4'
    scriptarguments:
      expectedValue:
        simple: demisto.com
      fields: {}
      path:
        simple: emailDomain.[0]
    separatecontext: false
    task:
      brand: ''
      id: c944f8d9-4b87-4af8-808d-a5a78e1cd956
      iscommand: false
      name: verify it's domain from email
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: c944f8d9-4b87-4af8-808d-a5a78e1cd956
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 967\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1012,\n      \"width\": 380,\n      \"x\": 450,\n      \"y\":\
  \ 50\n    }\n  }\n}"
