description: Dedup - Generic - Test
id: dedup_-_generic_-_test
inputs: []
name: Dedup - Generic - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: f8be0cc9-862b-46d4-890b-4c544fae2a86
      iscommand: false
      name: ''
      version: -1
    taskid: f8be0cc9-862b-46d4-890b-4c544fae2a86
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      1longtexttest: {}
      aaaa: {}
      addLabels:
        simple: '[{"Email/subject":"This is a subject"},{"Email/from":"test@demisto.com"}]'
      amarkdownsection: {}
      anothernumberpleasejusttomakesure: {}
      app: {}
      arcsightcaseid: {}
      assetid: {}
      attach: {}
      attachamenthash: {}
      attachmentcount: {}
      attachmentextension: {}
      attachmenthash: {}
      attachmentid: {}
      attachmentitem: {}
      attachmentname: {}
      attachmentsize: {}
      attachmenttype: {}
      backupowner: {}
      bbb: {}
      blah: {}
      bool1: {}
      bool2: {}
      booleansummary: {}
      boolfield: {}
      booltest: {}
      bugtraq: {}
      ccc: {}
      ccipaddress: {}
      compliance: {}
      constvalue: {}
      customFields: {}
      customfield: {}
      cve: {}
      cvss: {}
      daysbetweenreportcreation: {}
      department: {}
      departmentadmin: {}
      dest: {}
      destntdomain: {}
      details:
        simple: fdslkjflks sldkfj lsdfklsd flsdkfj sldkfjlsdfj lskdfj lsd flksd fsdlkfj
          sdlfj slkdfj lsdkfjlsdf sdlkfjsldfj sldkfj sldf sdlkfjsldfjslkdf sldkfjlsdkfj
          lsdfjlksdf jlsdfj lsdkfj dlskf jldskfjdskldlskf jsdlkfjsd lfskdf
      duration: {}
      emailbcc: {}
      emailbody: {}
      emailbodyformat: {}
      emailbodyhtml: {}
      emailcc: {}
      emailclientname: {}
      emailfrom: {}
      emailkeywords: {}
      emailmessageid: {}
      emailreceived: {}
      emailreplyto: {}
      emailreturnpath: {}
      emailsenderip: {}
      emailsize: {}
      emailsource: {}
      emailsubject: {}
      emailto: {}
      emailtocount: {}
      emailurlclicked: {}
      escalationdate: {}
      eventid: {}
      falses: {}
      fetchid: {}
      fetchtype: {}
      field1: {}
      field2: {}
      field3: {}
      field4: {}
      filehash: {}
      filename: {}
      filepath: {}
      hjhj: {}
      host: {}
      htmltypefield: {}
      id: {}
      important: {}
      importantfield: {}
      itaytestfield: {}
      labels: {}
      longtextone: {}
      longtexttoo: {}
      mailbody: {}
      malwarefamily: {}
      multilinetext: {}
      name: {}
      newmarkdownfield: {}
      newtextfield: {}
      numberplease: {}
      occurred: {}
      one: {}
      owner: {}
      phase: {}
      relatedincidentssummary: {}
      replacePlaybook: {}
      reporteduser: {}
      roles: {}
      screenshot: {}
      screenshot2: {}
      selector: {}
      severity: {}
      signature: {}
      single: {}
      single2: {}
      sla: {}
      source: {}
      sourceip: {}
      sourceip1: {}
      src: {}
      srcntdomain: {}
      srcuser: {}
      subcat: {}
      subcategory: {}
      systems: {}
      team: {}
      test: {}
      test111: {}
      test2: {}
      testfield: {}
      testhtml: {}
      timeassignedtolevel2: {}
      timefield1: {}
      timelevel1: {}
      tldr: {}
      tttttt: {}
      type: {}
      user: {}
      username: {}
      vendorid: {}
      vendorproduct: {}
      vulnerabilitycategory: {}
    separatecontext: false
    task:
      brand: Builtin
      id: d5d7a8f4-3f33-40ca-8c4c-2efcf05c18a6
      iscommand: true
      name: Add labels
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: d5d7a8f4-3f33-40ca-8c4c-2efcf05c18a6
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '13':
    id: '13'
    ignoreworker: false
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '16'
    note: false
    scriptarguments:
      CloseAsDuplicate:
        simple: 'false'
      DuplicateMethod:
        simple: ml
      DuplicateThreshold:
        simple: '0.5'
      IgnoreCloseIncidents:
        simple: 'yes'
      MaxNumberOfCandidates:
        simple: '1000'
      TimeField:
        simple: occurred
      TimeFrameHours:
        simple: '72'
    separatecontext: true
    task:
      brand: ''
      id: 416e8ba9-c12e-4d68-8ddd-2aa75fc70768
      iscommand: false
      name: Dedup - Generic
      playbookName: Dedup - Generic
      type: playbook
      version: -1
    taskid: 416e8ba9-c12e-4d68-8ddd-2aa75fc70768
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '14':
    id: '14'
    ignoreworker: false
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '17'
    note: false
    scriptarguments:
      CloseAsDuplicate:
        simple: 'false'
      DuplicateMethod:
        simple: rules
      DuplicateThreshold:
        simple: '0.5'
      IgnoreCloseIncidents:
        simple: 'yes'
      MaxNumberOfCandidates:
        simple: '1000'
      TimeField:
        simple: occurred
      TimeFrameHours:
        simple: '72'
    separatecontext: true
    task:
      brand: ''
      id: 93d4fe55-e59f-4ce9-8b7e-8918cc824160
      iscommand: false
      name: Dedup - Generic
      playbookName: Dedup - Generic
      type: playbook
      version: -1
    taskid: 93d4fe55-e59f-4ce9-8b7e-8918cc824160
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1245\n  }\n}"
  '15':
    id: '15'
    ignoreworker: false
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '18'
    note: false
    scriptarguments:
      CloseAsDuplicate:
        simple: 'false'
      DuplicateMethod:
        simple: text
      DuplicateThreshold:
        simple: '0.5'
      IgnoreCloseIncidents:
        simple: 'yes'
      MaxNumberOfCandidates:
        simple: '1000'
      TimeField:
        simple: occurred
      TimeFrameHours:
        simple: '72'
    separatecontext: true
    task:
      brand: ''
      id: d54e8ebc-4968-4df4-8f13-3d90e561a014
      iscommand: false
      name: Dedup - Generic
      playbookName: Dedup - Generic
      type: playbook
      version: -1
    taskid: d54e8ebc-4968-4df4-8f13-3d90e561a014
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1770\n  }\n}"
  '16':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: isSimilarIncidentFound
          operator: isTrue
      label: 'yes'
    id: '16'
    ignoreworker: false
    nexttasks:
      'yes':
      - '6'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 5e303a56-bab1-4118-8186-2f551e3d1140
      iscommand: false
      name: Check similar incident found
      type: condition
      version: -1
    taskid: 5e303a56-bab1-4118-8186-2f551e3d1140
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '17':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: isSimilarIncidentFound
          operator: isTrue
      label: 'yes'
    id: '17'
    ignoreworker: false
    nexttasks:
      'yes':
      - '8'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: aab53110-15f4-412d-89da-450f118053d8
      iscommand: false
      name: Check similar incident found
      type: condition
      version: -1
    taskid: aab53110-15f4-412d-89da-450f118053d8
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1420\n  }\n}"
  '18':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: isSimilarIncidentFound
          operator: isTrue
      label: 'yes'
    id: '18'
    ignoreworker: false
    nexttasks:
      'yes':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 7f12569b-35ba-4d36-88e8-005a1d419bd5
      iscommand: false
      name: Check similar incident found
      type: condition
      version: -1
    taskid: 7f12569b-35ba-4d36-88e8-005a1d419bd5
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1945\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '13'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: d39fded2-6952-4d23-83fa-52b88ffbff02
      iscommand: false
      name: Create duplicate incident
      scriptName: CreateDuplicateIncident
      type: regular
      version: -1
    taskid: d39fded2-6952-4d23-83fa-52b88ffbff02
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 583eb9d1-3bf8-40fe-8bd1-8b5f8b5ea95a
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 583eb9d1-3bf8-40fe-8bd1-8b5f8b5ea95a
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2120\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    task:
      brand: ''
      id: a68f0286-03d4-4efe-8c4f-171992f94c69
      iscommand: false
      name: Clear context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: a68f0286-03d4-4efe-8c4f-171992f94c69
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '14'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    task:
      brand: ''
      id: 4fd47061-a541-4b79-82dc-53ec24e22a7d
      iscommand: false
      name: Clear context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 4fd47061-a541-4b79-82dc-53ec24e22a7d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '15'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    task:
      brand: ''
      id: c2c728ce-95bf-4806-8093-99af479d5f41
      iscommand: false
      name: Clear context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: c2c728ce-95bf-4806-8093-99af479d5f41
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1595\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 2135,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
