description: ''
id: Palo Alto Networks Cortex Test
inputs: []
name: Palo Alto Networks Cortex Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: edf28dd0-abd7-4bd6-8247-fdc9093505af
      iscommand: false
      name: ''
      version: -1
    taskid: edf28dd0-abd7-4bd6-8247-fdc9093505af
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": -170\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      endTime: {}
      query: {}
      rangeValue: {}
      startTime: {}
      timeRange: {}
    separatecontext: false
    task:
      brand: ''
      description: Query Cortex Logging service
      id: fc21e1dd-eb73-4c6f-8a51-efa34e802a98
      iscommand: true
      name: Query Logs
      script: '|||cortex-query-logs'
      type: regular
      version: -1
    taskid: fc21e1dd-eb73-4c6f-8a51-efa34e802a98
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 195\n  }\n}"
  '10':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Logging.Traffic.Src
                root: Cortex
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Logging.Traffic.Dst
                root: Cortex
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Logging.Traffic.Rule
                root: Cortex
          operator: isExists
      label: 'yes'
    id: '10'
    ignoreworker: false
    nexttasks:
      'yes':
      - '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: bf212a19-2209-4316-860f-a879c39cd06c
      iscommand: false
      name: Verify Query Traffic Logs Outputs
      type: condition
      version: -1
    taskid: bf212a19-2209-4316-860f-a879c39cd06c
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 725\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '13'
    note: false
    scriptarguments:
      category: {}
      endTime: {}
      fields: {}
      hash: {}
      host: {}
      ip: {}
      query: {}
      rangeValue: {}
      startTime: {}
      timeRange: {}
      user: {}
    separatecontext: false
    task:
      brand: Palo Alto Networks Cortex
      description: TBD
      id: ccadc483-ddd0-4466-83e4-e7d1c55ea670
      iscommand: true
      name: cortex-query-traps-logs
      script: Palo Alto Networks Cortex|||cortex-query-traps-logs
      type: regular
      version: -1
    taskid: ccadc483-ddd0-4466-83e4-e7d1c55ea670
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 545\n  }\n}"
  '12':
    id: '12'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '14'
    note: false
    scriptarguments:
      category: {}
      endTime: {}
      fields: {}
      hash: {}
      host: {}
      ip: {}
      query: {}
      rangeValue: {}
      startTime: {}
      timeRange: {}
      user: {}
    separatecontext: false
    task:
      brand: Palo Alto Networks Cortex
      description: TBD
      id: 28a1aabd-6c4d-4f89-8164-ac13d30278b9
      iscommand: true
      name: cortex-query-analytics-logs
      script: Palo Alto Networks Cortex|||cortex-query-analytics-logs
      type: regular
      version: -1
    taskid: 28a1aabd-6c4d-4f89-8164-ac13d30278b9
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": -370,\n    \"y\": 545\n  }\n}"
  '13':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Logging.Traps.AgentID
                root: Cortex
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Logging.Traps.EndPointHeader.DeviceName
                root: Cortex
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Logging.Traps.EndPointHeader.AgentIP
                root: Cortex
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Logging.Traps.MessageData
                root: Cortex
          operator: isExists
      label: 'yes'
    id: '13'
    ignoreworker: false
    nexttasks:
      'yes':
      - '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: de7978f6-928b-4385-8479-1fd2fc37a82a
      iscommand: false
      name: Verify Query Traps Logs Outputs
      type: condition
      version: -1
    taskid: de7978f6-928b-4385-8479-1fd2fc37a82a
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 725\n  }\n}"
  '14':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Logging.Analytics.AgentID
                root: Cortex
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Logging.Analytics.EndPointHeader.DeviceName
                root: Cortex
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Logging.Analytics.EndPointHeader.AgentIP
                root: Cortex
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Logging.Analytics.MessageData
                root: Cortex
          operator: isExists
      label: 'yes'
    id: '14'
    ignoreworker: false
    nexttasks:
      'yes':
      - '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 33fe8ccd-134b-4f1b-8c6a-03dbb692800b
      iscommand: false
      name: Verify Query Analytics Logs Outputs
      type: condition
      version: -1
    taskid: 33fe8ccd-134b-4f1b-8c6a-03dbb692800b
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": -370,\n    \"y\": 725\n  }\n}"
  '2':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Cortex.Logging.id
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: Cortex.Logging.score
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: Cortex.Logging.action
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: Cortex.Logging.app
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: Cortex.Logging.dst
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: Cortex.Logging.rule
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: Cortex.Logging.src
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: Cortex.Logging.category-of-app
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: Cortex.Logging.srcloc
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: Cortex.Logging.dstloc
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: Cortex.Logging.characteristic-of-app
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: Cortex.Logging.device_name
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: Cortex.Logging.natdport
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: Cortex.Logging.natdst
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: Cortex.Logging.natsrc
          operator: isExists
      label: 'yes'
    id: '2'
    ignoreworker: false
    nexttasks:
      'yes':
      - '7'
      - '9'
      - '11'
      - '12'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: b41f9512-fb16-4568-8457-73b0e988f08c
      iscommand: false
      name: Verify Query Logs Outputs
      type: condition
      version: -1
    taskid: b41f9512-fb16-4568-8457-73b0e988f08c
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      description: Query Cortex Logging service according to pre-set queries
      id: 17527902-aa07-4acc-8db5-1f3aba1533f5
      iscommand: false
      name: Success
      type: title
      version: -1
    taskid: 17527902-aa07-4acc-8db5-1f3aba1533f5
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1220\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      add_to_context: {}
      brand_name:
        simple: Palo Alto Networks Cortex
      expect_data: {}
      instance_name: {}
    separatecontext: false
    task:
      brand: ''
      description: Execute FetchIncident for a given instance
      id: 4fb983b7-2e2b-4b89-8411-8f967774fd0f
      iscommand: false
      name: Fetch events
      scriptName: FetchFromInstance
      type: regular
      version: -1
    taskid: 4fb983b7-2e2b-4b89-8411-8f967774fd0f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1045\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 2a7f60cd-c668-4cb8-85af-ab7de14bfa33
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 2a7f60cd-c668-4cb8-85af-ab7de14bfa33
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 0\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    scriptarguments:
      action: {}
      endTime: {}
      fields: {}
      from_zone: {}
      hash: {}
      ip: {}
      port: {}
      query: {}
      rangeValue: {}
      rule: {}
      startTime: {}
      timeRange: {}
      to_zone: {}
      url: {}
    separatecontext: false
    task:
      brand: Palo Alto Networks Cortex
      description: TBD
      id: 1d338cf1-a603-4dd7-8eb6-92b5301287dd
      iscommand: true
      name: cortex-query-threat-logs
      script: Palo Alto Networks Cortex|||cortex-query-threat-logs
      type: regular
      version: -1
    taskid: 1d338cf1-a603-4dd7-8eb6-92b5301287dd
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 545\n  }\n}"
  '8':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Logging.Threat.Src
                root: Cortex
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Logging.Threat.Dst
                root: Cortex
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Logging.Threat.Rule
                root: Cortex
          operator: isExists
      label: 'yes'
    id: '8'
    ignoreworker: false
    nexttasks:
      'yes':
      - '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: c409f106-b13e-4566-8e43-60ad0756075e
      iscommand: false
      name: Verify Query Threat Logs Outputs
      type: condition
      version: -1
    taskid: c409f106-b13e-4566-8e43-60ad0756075e
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 725\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '10'
    note: false
    scriptarguments:
      action: {}
      endTime: {}
      fields: {}
      from_zone: {}
      ip: {}
      port: {}
      query: {}
      rangeValue: {}
      rule: {}
      startTime: {}
      timeRange: {}
      to_zone: {}
    separatecontext: false
    task:
      brand: Palo Alto Networks Cortex
      description: TBD
      id: a38e4c3a-283d-4056-82e3-db119769db60
      iscommand: true
      name: cortex-query-traffic-logs
      script: Palo Alto Networks Cortex|||cortex-query-traffic-logs
      type: regular
      version: -1
    taskid: a38e4c3a-283d-4056-82e3-db119769db60
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1455,\n      \"width\": 1660,\n      \"x\": -370,\n      \"y\"\
  : -170\n    }\n  }\n}"
