description: ''
id: ExtractURL Test
inputs: []
name: ExtractURL Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 5d2cb26b-7b81-481b-8ca1-57f48123a82d
      iscommand: false
      name: ''
      version: -1
    taskid: 5d2cb26b-7b81-481b-8ca1-57f48123a82d
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    quietmode: 0
    scriptarguments:
      text:
        simple: https://google.com?bla=www.nba.com&kuku=lalahttp://www.cnn.com&nana=http://1.2.3.4
      urlRegex: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Extract URLs from the given text and place them both as output
        and in the context of a playbook. If given an object, will convert to JSON.
      id: 404b82b0-817d-43e4-8d10-e4a244edc254
      iscommand: false
      name: ExtractURL
      script: ExtractURL
      type: regular
      version: -1
    taskid: 404b82b0-817d-43e4-8d10-e4a244edc254
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 230\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      'yes':
      - '4'
    note: false
    quietmode: 0
    scriptarguments:
      left:
        simple: ${URL.[0].Data}
      right:
        simple: https://google.com?bla=www.nba.com
      value:
        simple: ${URL.Data(val.indexOf('https://google.com?bla=www.nba.com&kuku=lalahttp://www.cnn.com&nana=http://1.2.3.4')
          === 0)}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: cd28849b-41e2-4c1e-80d9-7dd696b0d492
      iscommand: false
      name: Verify URL 1
      script: IsTrue
      type: condition
      version: -1
    taskid: cd28849b-41e2-4c1e-80d9-7dd696b0d492
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 446\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      'yes':
      - '5'
    note: false
    quietmode: 0
    scriptarguments:
      left:
        simple: ${URL.[1].Data}
      right:
        simple: www.nba.com
      value:
        simple: ${URL.Data(val.indexOf('www.nba.com') === 0)}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 0f08a07c-28ae-406f-88f3-24bf73c97736
      iscommand: false
      name: Verify URL 2
      script: IsTrue
      type: condition
      version: -1
    taskid: 0f08a07c-28ae-406f-88f3-24bf73c97736
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 687\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      'yes':
      - '6'
    note: false
    quietmode: 0
    scriptarguments:
      left:
        simple: ${URL.[2].Data}
      right:
        simple: ${.=val.URL.Data.indexOf('www.nba.com') !== -1}
      value:
        simple: ${URL.Data(val.indexOf('http://www.cnn.com') === 0)}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 2a245d9f-b559-40a3-854f-5d432dda4d7b
      iscommand: false
      name: Verify URL 3
      script: IsTrue
      type: condition
      version: -1
    taskid: 2a245d9f-b559-40a3-854f-5d432dda4d7b
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 933\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      'yes':
      - '7'
    note: false
    quietmode: 0
    scriptarguments:
      left:
        simple: ${URL.[3].Data}
      right:
        simple: http://www.cnn.com
      value:
        simple: ${URL.Data(val.indexOf('http://1.2.3.4') === 0)}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: c49b88ed-9a31-4a9b-882b-8d3f001afa69
      iscommand: false
      name: Verify URL 4
      script: IsTrue
      type: condition
      version: -1
    taskid: c49b88ed-9a31-4a9b-882b-8d3f001afa69
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 1183\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: Done
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: b3170402-a244-4e74-86fb-788e912fb50a
      iscommand: false
      name: Done
      script: Print
      type: regular
      version: -1
    taskid: b3170402-a244-4e74-86fb-788e912fb50a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 1427\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {\n    \"2_4_yes\": 0.72\n  },\n  \"paper\": {\n\
  \    \"dimensions\": {\n      \"height\": 1472,\n      \"width\": 380,\n      \"\
  x\": 450,\n      \"y\": 50\n    }\n  }\n}"
