name: Request review from pack contributor
on:
  pull_request:
    branches:
      - master

jobs:
  request_pr_review:
    runs-on: ubuntu-latest
    steps:
#      - name: Dump Github context
#        env:
#          GITHUB_CONTEXT: ${{ toJson(github) }}
#        run: echo "$GITHUB_CONTEXT"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements-py3.txt
      - name: Check author and request review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          echo "New PR number is $PR_NUMBER"
          python .github/workflows/helper_scripts/request_contributor_review.py --pr_number $PR_NUMBER --github_token $GITHUB_TOKEN
