id: Tanium Threat Response Test
version: -1
vcShouldKeepItemLegacyProdMachine: false
name: Tanium Threat Response Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 803d5b6f-3df7-4f01-8456-d88137a3cc27
    type: start
    task:
      id: 803d5b6f-3df7-4f01-8456-d88137a3cc27
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 31cf23d5-66f0-4efa-82bf-a6a83ac599c8
    type: regular
    task:
      id: 31cf23d5-66f0-4efa-82bf-a6a83ac599c8
      version: -1
      name: Clear context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: aa5927c9-a995-4a96-8c56-33593b51418f
    type: regular
    task:
      id: aa5927c9-a995-4a96-8c56-33593b51418f
      version: -1
      name: Get intel doc by ID
      description: Returns a intel document object based on ID.
      script: '|||tanium-tr-get-intel-doc-by-id'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      intel-doc-id:
        simple: "64"
      retry-count:
        simple: "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 515
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 28295147-852c-4f5f-82aa-34d6c61635a6
    type: title
    task:
      id: 28295147-852c-4f5f-82aa-34d6c61635a6
      version: -1
      name: Query lists commands
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "25"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2090
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: 58c9493b-f2ae-4c29-8e66-986faa375a5e
    type: title
    task:
      id: 58c9493b-f2ae-4c29-8e66-986faa375a5e
      version: -1
      name: Getters
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: a95b8ce0-9c3e-4344-8c76-8afeb57d20c3
    type: regular
    task:
      id: a95b8ce0-9c3e-4344-8c76-8afeb57d20c3
      version: -1
      name: Get intel docs list
      description: Returns a list of all intel documents.
      script: '|||tanium-tr-list-intel-docs'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      limit: {}
      offset: {}
      retry-count:
        simple: "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2410
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: 2e9dcd84-70f2-46bd-8d31-4a51dfebad62
    type: regular
    task:
      id: 2e9dcd84-70f2-46bd-8d31-4a51dfebad62
      version: -1
      name: Get alerts list
      description: Returns a list of all alerts.
      script: '|||tanium-tr-list-alerts'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      computer-ip-address: {}
      computer-name: {}
      intel-doc-id: {}
      limit: {}
      offset: {}
      priority: {}
      retry-count:
        simple: "3"
      scan-config-id: {}
      severity: {}
      state: {}
      type: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2585
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: 79275845-2266-4bf2-8618-8ce7f8daf7fe
    type: regular
    task:
      id: 79275845-2266-4bf2-8618-8ce7f8daf7fe
      version: -1
      name: Get connections list
      description: Returns all connections.
      script: '|||tanium-tr-list-connections'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      limit:
        simple: "1"
      offset: {}
      retry-count:
        simple: "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2760
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: d1696cf6-bda7-448d-88c5-4ff806c5491a
    type: regular
    task:
      id: d1696cf6-bda7-448d-88c5-4ff806c5491a
      version: -1
      name: Get snapshots list by connection
      description: Returns all snapshots of a single connection.
      script: '|||tanium-tr-list-snapshots-by-connection'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      connection-name:
        simple: taniumlinux
      connection_name:
        complex:
          root: Tanium
          accessor: Connection.Name
          transformers:
          - operator: FirstArrayElement
      limit:
        simple: "1"
      offset: {}
      retry-count:
        simple: "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2935
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: 9ebf8fb7-a7ff-42f7-85ec-66c2ec02bfc7
    type: regular
    task:
      id: 9ebf8fb7-a7ff-42f7-85ec-66c2ec02bfc7
      version: -1
      name: Get local snapshots list by connection
      description: Returns all local snapshots of a single connection.
      script: '|||tanium-tr-list-local-snapshots-by-connection'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      connection-name:
        simple: taniumlinux
      connection_name:
        complex:
          root: Tanium
          accessor: Connection.Name
          transformers:
          - operator: FirstArrayElement
      limit: {}
      offset: {}
      retry-count:
        simple: "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 3110
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: 303b18b5-2988-4cbe-850a-d4134b9c978d
    type: regular
    task:
      id: 303b18b5-2988-4cbe-850a-d4134b9c978d
      version: -1
      name: Get labels list
      description: Returns all available labels in the system.
      script: '|||tanium-tr-list-labels'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      limit: {}
      offset: {}
      retry-count:
        simple: "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 3285
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "11":
    id: "11"
    taskid: e89b17c6-4818-4f92-825c-16cfba5dd3d3
    type: title
    task:
      id: e89b17c6-4818-4f92-825c-16cfba5dd3d3
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 3460
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "12":
    id: "12"
    taskid: 44b3c0ab-41bc-4b59-8edf-31a401a1357d
    type: regular
    task:
      id: 44b3c0ab-41bc-4b59-8edf-31a401a1357d
      version: -1
      name: Get alert by ID
      description: Returns alert object based on ID.
      script: '|||tanium-tr-get-alert-by-id'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      alert-id:
        simple: "1"
      retry-count:
        simple: "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 865
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "13":
    id: "13"
    taskid: 978ed303-c4e2-41d9-8707-0ec42c65b221
    type: regular
    task:
      id: 978ed303-c4e2-41d9-8707-0ec42c65b221
      version: -1
      name: Update alert state
      description: Update the state of a single alert.
      script: '|||tanium-tr-alert-update-state'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      alert-id:
        simple: "1"
      retry-count:
        simple: "3"
      state:
        simple: Resolved
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 690
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "14":
    id: "14"
    taskid: 2410426f-073b-4dc2-8051-e4f2c975d781
    type: condition
    task:
      id: 2410426f-073b-4dc2-8051-e4f2c975d781
      version: -1
      name: Validate alert state
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "15"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: Tanium.Alert.State
            iscontext: true
          right:
            value:
              simple: Resolved
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1040
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "15":
    id: "15"
    taskid: d19c3889-b9f1-4240-831b-c03f4396dc24
    type: regular
    task:
      id: d19c3889-b9f1-4240-831b-c03f4396dc24
      version: -1
      name: Update alert state
      description: Update the state of a single alert.
      script: '|||tanium-tr-alert-update-state'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      alert-id:
        simple: "1"
      retry-count:
        simple: "3"
      state:
        simple: Unresolved
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1215
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "16":
    id: "16"
    taskid: 0d8936f7-3cec-48a5-874c-36933354fca8
    type: regular
    task:
      id: 0d8936f7-3cec-48a5-874c-36933354fca8
      version: -1
      name: Get connection by name
      description: Returns a connection object based on name.
      script: '|||tanium-tr-get-connection-by-name'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "24"
    scriptarguments:
      connection-name:
        simple: taniumlinux
      retry-count:
        simple: "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1565
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "17":
    id: "17"
    taskid: 7e6fe876-79ac-487d-83e3-50909fa87a22
    type: regular
    task:
      id: 7e6fe876-79ac-487d-83e3-50909fa87a22
      version: -1
      name: Get label by ID
      description: Returns label object based on ID.
      script: '|||tanium-tr-get-label-by-id'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      label-id:
        simple: "1"
      retry-count:
        simple: "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1390
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "23":
    id: "23"
    taskid: 2f56e2c7-1e4c-4f74-8a40-2a5ed3a2fcdf
    type: regular
    task:
      id: 2f56e2c7-1e4c-4f74-8a40-2a5ed3a2fcdf
      version: -1
      name: tanium-tr-get-evidence-by-id
      description: Gets evidence by evidence ID.
      script: '|||tanium-tr-get-evidence-by-id'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      evidence-id:
        simple: "29"
      retry-count:
        simple: "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1915
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "24":
    id: "24"
    taskid: e967d002-be62-43b2-8350-2ecd022cbf4d
    type: regular
    task:
      id: e967d002-be62-43b2-8350-2ecd022cbf4d
      version: -1
      name: Create connection
      description: Creates a local or remote connection.
      script: '|||tanium-tr-create-connection'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "23"
    scriptarguments:
      connection-timeout: {}
      destination:
        simple: taniumlinux
      destination-type:
        simple: ip_address
      remote:
        simple: "False"
      retry-count:
        simple: "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1740
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "25":
    id: "25"
    taskid: 44572f88-5737-44a7-8393-de57801d4aab
    type: regular
    task:
      id: 44572f88-5737-44a7-8393-de57801d4aab
      version: -1
      name: Clear context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2235
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 3475,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
